package model

import (
	"context"
	"time"
)

// MockLoader implements Loader and Mutator using static mock data.
type MockLoader struct{}

func (MockLoader) CordonNode(_ context.Context, _ string) error   { return nil }
func (MockLoader) UncordonNode(_ context.Context, _ string) error { return nil }
func (MockLoader) DrainNode(_ context.Context, _ string) error    { return nil }

func (MockLoader) FetchNodes() ([]Node, string, error) {
	return MockNodes(), "mock-cluster", nil
}

func MockNodes() []Node {
	return []Node{
		{
			Name:                    "ip-10-0-1-100.ec2.internal",
			Status:                  StatusReady,
			Roles:                   "worker",
			Age:                     "45d",
			CreationTimestamp:       time.Now().Add(-45 * 24 * time.Hour),
			Arch:                    "amd64",
			NodeGroup:               "workers-prod",
			CapacityType:            "on-demand",
			KarpenterStatus:         "Eligible",
			Instance:                "m5.xlarge",
			Zone:                    "us-east-1a",
			CPU:                     "4/4",
			Mem:                     "12/16Gi",
			CPUPercent:              62.0,
			MemPercent:              75.0,
			PodCount:                18,
			PodCapacity:             110,
			Cordoned:                false,
			KubeletVersion:          "v1.27.3",
			OSImage:                 "Amazon Linux 2 (5.10)",
			KernelVersion:           "5.10.68-62.173.amzn2.x86_64",
			ContainerRuntimeVersion: "containerd://1.6.6",
			InternalIP:              "10.0.1.100",
			ExternalIP:              "54.12.34.56",
			PodCIDR:                 "192.168.1.0/24",
			AllocatableCPU:          "3920m",
			AllocatableMem:          "14.4Gi",
			Taints:                  []string{},
			Labels: map[string]string{
				"kubernetes.io/arch":               "amd64",
				"kubernetes.io/os":                 "linux",
				"node.kubernetes.io/instance-type": "m5.xlarge",
				"topology.kubernetes.io/zone":      "us-east-1a",
			},
			Conditions: []Condition{
				{Type: "MemoryPressure", Status: "False", Reason: "KubeletHasSufficientMemory", Message: "kubelet has sufficient memory available"},
				{Type: "DiskPressure", Status: "False", Reason: "KubeletHasNoDiskPressure", Message: "kubelet has no disk pressure"},
				{Type: "PIDPressure", Status: "False", Reason: "KubeletHasSufficientPID", Message: "kubelet has sufficient PID available"},
				{Type: "Ready", Status: "True", Reason: "KubeletReady", Message: "kubelet is posting ready status"},
			},
			Events: []Event{
				{Type: "Normal", Reason: "NodeReady", Message: "Node became ready", Count: 1, Age: "45d", Source: "kubelet"},
				{Type: "Warning", Reason: "OOMKilling", Message: "Memory cgroup out of memory: Kill process 12345", Count: 3, Age: "2h", Source: "kernel"},
				{Type: "Warning", Reason: "FreeDiskSpaceFailed", Message: "Failed to garbage collect required amount of images", Count: 12, Age: "4h", Source: "kubelet"},
				{Type: "Normal", Reason: "NodeNotReady", Message: "Node ip-10-0-1-100 status is now: NodeNotReady", Count: 1, Age: "45d", Source: "node-controller"},
			},
			Pods: []Pod{
				{Name: "coredns-5d78c9869d-abc12", Namespace: "kube-system", Phase: "Running", Ready: true, Restarts: 0, Age: "45d", Image: "coredns:1.10.1"},
				{Name: "aws-node-xk9p2", Namespace: "kube-system", Phase: "Running", Ready: true, Restarts: 1, Age: "45d", Image: "amazon-k8s-cni:v1.12.6"},
				{Name: "kube-proxy-m7n3q", Namespace: "kube-system", Phase: "Running", Ready: true, Restarts: 0, Age: "45d", Image: "kube-proxy:v1.27.3"},
				{Name: "myapp-deployment-7d9f8b-xp2k1", Namespace: "production", Phase: "Running", Ready: true, Restarts: 0, Age: "12d", Image: "myapp:v2.4.1"},
				{Name: "myapp-deployment-7d9f8b-lm3n4", Namespace: "production", Phase: "Running", Ready: true, Restarts: 0, Age: "12d", Image: "myapp:v2.4.1"},
				{Name: "redis-cache-0", Namespace: "production", Phase: "Running", Ready: true, Restarts: 2, Age: "30d", Image: "redis:7.0-alpine"},
				{Name: "fluentd-aggregator-p9q1r", Namespace: "logging", Phase: "Running", Ready: true, Restarts: 0, Age: "45d", Image: "fluentd:v1.16"},
				{Name: "crashloop-worker-abc99", Namespace: "production", Phase: "Running", Ready: false, Restarts: 14, Age: "2d", Image: "worker:v1.0.0"},
			},
		},
		{
			Name:                    "ip-10-0-2-200.ec2.internal",
			Status:                  StatusReady,
			Roles:                   "worker",
			Age:                     "12d",
			CreationTimestamp:       time.Now().Add(-12 * 24 * time.Hour),
			Arch:                    "amd64",
			NodeGroup:               "workers-prod",
			CapacityType:            "spot",
			KarpenterStatus:         "Disrupting",
			Instance:                "m5.2xlarge",
			Zone:                    "us-east-1b",
			CPU:                     "6/8",
			Mem:                     "20/32Gi",
			CPUPercent:              75.0,
			MemPercent:              62.5,
			PodCount:                34,
			PodCapacity:             110,
			Cordoned:                false,
			KubeletVersion:          "v1.27.3",
			OSImage:                 "Amazon Linux 2 (5.10)",
			KernelVersion:           "5.10.68-62.173.amzn2.x86_64",
			ContainerRuntimeVersion: "containerd://1.6.6",
			InternalIP:              "10.0.2.200",
			ExternalIP:              "54.23.45.67",
			PodCIDR:                 "192.168.2.0/24",
			AllocatableCPU:          "7910m",
			AllocatableMem:          "29.6Gi",
			Taints:                  []string{"dedicated=gpu:NoSchedule"},
			Labels: map[string]string{
				"kubernetes.io/arch":               "amd64",
				"kubernetes.io/os":                 "linux",
				"node.kubernetes.io/instance-type": "m5.2xlarge",
				"topology.kubernetes.io/zone":      "us-east-1b",
			},
			Conditions: []Condition{
				{Type: "MemoryPressure", Status: "False", Reason: "KubeletHasSufficientMemory", Message: "kubelet has sufficient memory available"},
				{Type: "DiskPressure", Status: "False", Reason: "KubeletHasNoDiskPressure", Message: "kubelet has no disk pressure"},
				{Type: "PIDPressure", Status: "False", Reason: "KubeletHasSufficientPID", Message: "kubelet has sufficient PID available"},
				{Type: "Ready", Status: "True", Reason: "KubeletReady", Message: "kubelet is posting ready status"},
			},
		},
		{
			Name:                    "ip-10-0-3-50.ec2.internal",
			Status:                  StatusNotReadySchedulingDisabled,
			Roles:                   "worker",
			Age:                     "3d",
			CreationTimestamp:       time.Now().Add(-3 * 24 * time.Hour),
			Arch:                    "amd64",
			NodeGroup:               "workers-spot",
			CapacityType:            "spot",
			KarpenterStatus:         "Blocked",
			Instance:                "c5.large",
			Zone:                    "us-east-1c",
			CPU:                     "0/2",
			Mem:                     "1/4Gi",
			CPUPercent:              5.0,
			MemPercent:              25.0,
			PodCount:                2,
			PodCapacity:             110,
			Cordoned:                true,
			KubeletVersion:          "v1.27.3",
			OSImage:                 "Amazon Linux 2 (5.10)",
			KernelVersion:           "5.10.68-62.173.amzn2.x86_64",
			ContainerRuntimeVersion: "containerd://1.6.6",
			InternalIP:              "10.0.3.50",
			ExternalIP:              "",
			PodCIDR:                 "192.168.3.0/24",
			AllocatableCPU:          "1930m",
			AllocatableMem:          "3.5Gi",
			Taints:                  []string{"node.kubernetes.io/not-ready:NoExecute"},
			Labels: map[string]string{
				"kubernetes.io/arch":               "amd64",
				"kubernetes.io/os":                 "linux",
				"node.kubernetes.io/instance-type": "c5.large",
				"topology.kubernetes.io/zone":      "us-east-1c",
				"spot":                             "true",
			},
			Conditions: []Condition{
				{Type: "MemoryPressure", Status: "True", Reason: "KubeletHasInsufficientMemory", Message: "kubelet has insufficient memory available"},
				{Type: "DiskPressure", Status: "False", Reason: "KubeletHasNoDiskPressure", Message: "kubelet has no disk pressure"},
				{Type: "PIDPressure", Status: "False", Reason: "KubeletHasSufficientPID", Message: "kubelet has sufficient PID available"},
				{Type: "Ready", Status: "False", Reason: "KubeletNotReady", Message: "container runtime network not ready"},
			},
		},
		{
			Name:                    "ip-10-0-1-150.ec2.internal",
			Status:                  StatusReady,
			Roles:                   "control-plane",
			Age:                     "60d",
			CreationTimestamp:       time.Now().Add(-60 * 24 * time.Hour),
			Arch:                    "amd64",
			NodeGroup:               "control-plane",
			CapacityType:            "on-demand",
			Instance:                "m5.large",
			Zone:                    "us-east-1a",
			CPU:                     "1/2",
			Mem:                     "3/8Gi",
			CPUPercent:              38.0,
			MemPercent:              37.5,
			PodCount:                9,
			PodCapacity:             110,
			Cordoned:                false,
			KubeletVersion:          "v1.27.3",
			OSImage:                 "Amazon Linux 2 (5.10)",
			KernelVersion:           "5.10.68-62.173.amzn2.x86_64",
			ContainerRuntimeVersion: "containerd://1.6.6",
			InternalIP:              "10.0.1.150",
			ExternalIP:              "",
			PodCIDR:                 "192.168.0.0/24",
			AllocatableCPU:          "1930m",
			AllocatableMem:          "7.2Gi",
			Taints:                  []string{"node-role.kubernetes.io/control-plane:NoSchedule"},
			Labels: map[string]string{
				"kubernetes.io/arch":                    "amd64",
				"kubernetes.io/os":                      "linux",
				"node-role.kubernetes.io/control-plane": "",
				"node-role.kubernetes.io/master":        "",
				"node.kubernetes.io/instance-type":      "m5.large",
				"topology.kubernetes.io/zone":           "us-east-1a",
			},
			Conditions: []Condition{
				{Type: "MemoryPressure", Status: "False", Reason: "KubeletHasSufficientMemory", Message: "kubelet has sufficient memory available"},
				{Type: "DiskPressure", Status: "False", Reason: "KubeletHasNoDiskPressure", Message: "kubelet has no disk pressure"},
				{Type: "PIDPressure", Status: "False", Reason: "KubeletHasSufficientPID", Message: "kubelet has sufficient PID available"},
				{Type: "Ready", Status: "True", Reason: "KubeletReady", Message: "kubelet is posting ready status"},
			},
		},
		{
			Name:                    "ip-10-0-2-175.ec2.internal",
			Status:                  StatusUnknown,
			Roles:                   "worker",
			Age:                     "1d",
			CreationTimestamp:       time.Now().Add(-24 * time.Hour),
			Arch:                    "amd64",
			NodeGroup:               "workers-spot",
			CapacityType:            "spot",
			KarpenterStatus:         "Drifted",
			Instance:                "t3.medium",
			Zone:                    "us-east-1b",
			CPU:                     "0/2",
			Mem:                     "0/4Gi",
			CPUPercent:              0.0,
			MemPercent:              0.0,
			PodCount:                0,
			PodCapacity:             110,
			Cordoned:                false,
			KubeletVersion:          "v1.27.1",
			OSImage:                 "Amazon Linux 2 (5.10)",
			KernelVersion:           "5.10.68-62.173.amzn2.x86_64",
			ContainerRuntimeVersion: "containerd://1.6.6",
			InternalIP:              "10.0.2.175",
			ExternalIP:              "",
			PodCIDR:                 "192.168.4.0/24",
			AllocatableCPU:          "1930m",
			AllocatableMem:          "3.4Gi",
			Taints:                  []string{"node.kubernetes.io/unreachable:NoExecute"},
			Labels: map[string]string{
				"kubernetes.io/arch":               "amd64",
				"kubernetes.io/os":                 "linux",
				"node.kubernetes.io/instance-type": "t3.medium",
				"topology.kubernetes.io/zone":      "us-east-1b",
				"spot":                             "true",
			},
			Conditions: []Condition{
				{Type: "MemoryPressure", Status: "Unknown", Reason: "NodeStatusUnknown", Message: "Kubelet stopped posting node status"},
				{Type: "DiskPressure", Status: "Unknown", Reason: "NodeStatusUnknown", Message: "Kubelet stopped posting node status"},
				{Type: "PIDPressure", Status: "Unknown", Reason: "NodeStatusUnknown", Message: "Kubelet stopped posting node status"},
				{Type: "Ready", Status: "Unknown", Reason: "NodeStatusUnknown", Message: "Kubelet stopped posting node status"},
			},
		},
	}
}
